services:

  # =====================================
  # POSTGRES ANALYTICS
  # =====================================

  postgres:
    image: postgres:16
    container_name: actuaria_postgres
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  # =====================================
  # POSTGRES AIRFLOW METADATA
  # =====================================

  airflow-postgres:
    image: postgres:16
    container_name: airflow_postgres
    restart: always

    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}

    ports:
      - "5433:5432"

    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIRFLOW_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  # =====================================
  # AIRFLOW INIT
  # =====================================

  airflow-init:

    build:
      context: .

    image: actuaria-airflow:2.10.5

    restart: "no"

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Sao_Paulo
      AIRFLOW_UID: ${AIRFLOW_UID}
      PYTHONPATH: /opt/airflow

      # Banco Analytics
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sql:/opt/airflow/sql
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config

    command:
      - bash
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true


  # =====================================
  # AIRFLOW WEBSERVER
  # =====================================

  airflow-webserver:

    build:
      context: .

    image: actuaria-airflow:2.10.5

    container_name: airflow_webserver

    restart: always

    depends_on:
      airflow-postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Sao_Paulo
      AIRFLOW_UID: ${AIRFLOW_UID}
      PYTHONPATH: /opt/airflow

      # Banco Analytics
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sql:/opt/airflow/sql
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config

    command:
      - airflow
      - webserver


  # =====================================
  # AIRFLOW SCHEDULER
  # =====================================

  airflow-scheduler:

    build:
      context: .

    image: actuaria-airflow:2.10.5

    container_name: airflow_scheduler

    restart: always

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Sao_Paulo
      AIRFLOW_UID: ${AIRFLOW_UID}
      PYTHONPATH: /opt/airflow

      # Banco Analytics
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sql:/opt/airflow/sql
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ./config:/opt/airflow/config

    command:
      - airflow
      - scheduler


volumes:

  postgres_data:

  airflow_postgres_data: