FROM python:3.12-slim

WORKDIR /app

COPY requirements.streamlit.txt .

RUN pip install --no-cache-dir -r requirements.streamlit.txt

COPY streamlit_app/ .

COPY src/ ./src/

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]